name: "Get persistent value"
description: "Gets a value that persists through GitHub Actions jobs and workflows."
inputs:
  unique_key:
    description: "Your secret unique key (see README.md on how to get one)."
    required: true
  key:
    description: "The key to retrieve the value with."
    required: true
outputs:
  value:
    description: "The value that was stored."
runs:
  using: "node12"
  main: "dist/index.js"
