on: workflow_dispatch

jobs:
  get_persistent_value_job:
    runs-on: ubuntu-latest
    name: Get a persistent value
    steps:
      - name: Set a persistent value
        id: set_persistent_value_step
        uses: aaimio/set-persistent-value@master
        with:
          unique_key: ${{ secrets.UNIQUE_KEY }}
          key: set_persistent_value_test
          value: "This is a test value"
      - name: Get a persistent value
        id: get_persistent_value_step
        uses: aaimio/get-persistent-value@master
        with:
          unique_key: ${{ secrets.UNIQUE_KEY }}
          key: set_persistent_value_test
      - name: Return a persistent value
        run: echo "The returned value is '${{ steps.get_persistent_value_step.outputs.value }}'"
